// <auto-generated />
namespace SitecorePoweredBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SitecoreDBv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SitecoreDBv3));
        
        string IMigrationMetadata.Id
        {
            get { return "202302252107186_SitecoreDBv3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
